/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: the process is up */
        get: operations["read_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: the database answers */
        get: operations["read_readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List patients */
        get: operations["list_patients_patients_get"];
        put?: never;
        /** Create a patient */
        post: operations["create_patient_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patient counts for the dashboard */
        get: operations["read_patient_stats_patients_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a patient */
        get: operations["read_patient_patients__patient_id__get"];
        /** Replace a patient */
        put: operations["update_patient_patients__patient_id__put"];
        post?: never;
        /** Delete a patient and their notes */
        delete: operations["delete_patient_patients__patient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a patient's notes */
        get: operations["list_notes_patients__patient_id__notes_get"];
        put?: never;
        /** Add a clinical note */
        post: operations["create_note_patients__patient_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a note */
        delete: operations["delete_note_patients__patient_id__notes__note_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Human-readable summary of the profile and notes */
        get: operations["read_summary_patients__patient_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BloodType
         * @enum {string}
         */
        BloodType: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-";
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["FieldError"][];
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** NoteCreate */
        NoteCreate: {
            /** Content */
            content: string;
            /**
             * Noted At
             * Format: date-time
             * @description When the observation was made.
             */
            noted_at: string;
        };
        /** NoteListResponse */
        NoteListResponse: {
            /** Items */
            items: components["schemas"]["NoteRead"][];
            /** Total */
            total: number;
        };
        /** NoteRead */
        NoteRead: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Noted At
             * Format: date-time
             */
            noted_at: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
        };
        /** PatientCreate */
        PatientCreate: {
            /** Address Line1 */
            address_line1: string;
            /** Address Line2 */
            address_line2?: string | null;
            /**
             * Allergies
             * @default []
             */
            allergies: string[];
            blood_type?: components["schemas"]["BloodType"] | null;
            /** City */
            city: string;
            /**
             * Conditions
             * @default []
             */
            conditions: string[];
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** Email */
            email?: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Last Visit At */
            last_visit_at?: string | null;
            /** Phone */
            phone: string;
            /** Postal Code */
            postal_code: string;
            /** State */
            state: string;
            /** @default active */
            status: components["schemas"]["PatientStatus"];
        };
        /** PatientListResponse */
        PatientListResponse: {
            /** Items */
            items: components["schemas"]["PatientRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            readonly total_pages: number;
        };
        /** PatientRead */
        PatientRead: {
            /** Address Line1 */
            address_line1: string;
            /** Address Line2 */
            address_line2: string | null;
            /** Age */
            readonly age: number;
            /** Allergies */
            allergies: string[];
            blood_type: components["schemas"]["BloodType"] | null;
            /** City */
            city: string;
            /** Conditions */
            conditions: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** Email */
            email: string | null;
            /** First Name */
            first_name: string;
            /** Full Name */
            readonly full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Name */
            last_name: string;
            /** Last Visit At */
            last_visit_at: string | null;
            /** Phone */
            phone: string;
            /** Postal Code */
            postal_code: string;
            /** State */
            state: string;
            status: components["schemas"]["PatientStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PatientSortField
         * @enum {string}
         */
        PatientSortField: "last_name" | "first_name" | "age" | "last_visit" | "status" | "created_at";
        /** PatientStats */
        PatientStats: {
            /** By Status */
            by_status: components["schemas"]["StatusCount"][];
            /** New Last 30 Days */
            new_last_30_days: number;
            /** Total */
            total: number;
            /** Visits Last 30 Days */
            visits_last_30_days: number;
            /** Without Recent Visit */
            without_recent_visit: number;
        };
        /**
         * PatientStatus
         * @enum {string}
         */
        PatientStatus: "active" | "pending" | "inactive" | "discharged";
        /** PatientSummary */
        PatientSummary: {
            clinical: components["schemas"]["SummaryClinical"];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Generated By */
            generated_by: string;
            identifiers: components["schemas"]["SummaryIdentifiers"];
            /** Narrative */
            narrative: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
        };
        /** PatientUpdate */
        PatientUpdate: {
            /** Address Line1 */
            address_line1: string;
            /** Address Line2 */
            address_line2?: string | null;
            /**
             * Allergies
             * @default []
             */
            allergies: string[];
            blood_type?: components["schemas"]["BloodType"] | null;
            /** City */
            city: string;
            /**
             * Conditions
             * @default []
             */
            conditions: string[];
            /**
             * Date Of Birth
             * Format: date
             */
            date_of_birth: string;
            /** Email */
            email?: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Last Visit At */
            last_visit_at?: string | null;
            /** Phone */
            phone: string;
            /** Postal Code */
            postal_code: string;
            /** State */
            state: string;
            /** @default active */
            status: components["schemas"]["PatientStatus"];
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Database
             * @constant
             */
            database: "ok";
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
        /** StatusCount */
        StatusCount: {
            /** Count */
            count: number;
            status: components["schemas"]["PatientStatus"];
        };
        /** SummaryClinical */
        SummaryClinical: {
            /** Allergies */
            allergies: string[];
            /** Conditions */
            conditions: string[];
            /** Last Visit At */
            last_visit_at: string | null;
            /** Note Count */
            note_count: number;
        };
        /** SummaryIdentifiers */
        SummaryIdentifiers: {
            /** Age */
            age: number;
            blood_type: components["schemas"]["BloodType"] | null;
            /** Date Of Birth */
            date_of_birth: string;
            /** Full Name */
            full_name: string;
            status: components["schemas"]["PatientStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    read_readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_patients_patients_get: {
        parameters: {
            query?: {
                search?: string | null;
                status?: components["schemas"]["PatientStatus"] | null;
                sort?: components["schemas"]["PatientSortField"];
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientListResponse"];
                };
            };
            /** @description Patient not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_patient_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRead"];
                };
            };
            /** @description Patient not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_patient_stats_patients_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientStats"];
                };
            };
            /** @description Patient not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_patient_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRead"];
                };
            };
            /** @description Patient not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_patient_patients__patient_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRead"];
                };
            };
            /** @description Patient not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_patient_patients__patient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Patient not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_notes_patients__patient_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteListResponse"];
                };
            };
            /** @description Patient or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_note_patients__patient_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"];
                };
            };
            /** @description Patient or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_note_patients__patient_id__notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Patient or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_summary_patients__patient_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientSummary"];
                };
            };
            /** @description Patient or note not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
