name: pr-title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: read

concurrency:
  group: pr-title-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-title:
    name: Conventional commit title
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
            docs
            test
            ci
            refactor
          requireScope: false
